//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Db_Hospital_Management_EntityFramework.MyDbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MY_Db_Hospital_ManagmentEntities : DbContext
    {
        public MY_Db_Hospital_ManagmentEntities()
            : base("name=MY_Db_Hospital_ManagmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_M_Lookup_Hedar> A_M_Lookup_Hedar { get; set; }
        public virtual DbSet<A_M_Lookup_Line> A_M_Lookup_Line { get; set; }
        public virtual DbSet<M_Client_Registration> M_Client_Registration { get; set; }
        public virtual DbSet<M_Department_Information> M_Department_Information { get; set; }
        public virtual DbSet<M_Designation_Information> M_Designation_Information { get; set; }
        public virtual DbSet<M_Employee_Information> M_Employee_Information { get; set; }
        public virtual DbSet<M_Hospital_Information> M_Hospital_Information { get; set; }
        public virtual DbSet<M_Item_Information> M_Item_Information { get; set; }
        public virtual DbSet<M_Material_Type_Infromation> M_Material_Type_Infromation { get; set; }
        public virtual DbSet<M_Packing> M_Packing { get; set; }
        public virtual DbSet<M_Person_Information> M_Person_Information { get; set; }
        public virtual DbSet<M_Tax_Type_Information> M_Tax_Type_Information { get; set; }
        public virtual DbSet<M_Unit_Information> M_Unit_Information { get; set; }
        public virtual DbSet<M_User_Login_Information> M_User_Login_Information { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<T_Medicen_Sale_Hedar> T_Medicen_Sale_Hedar { get; set; }
        public virtual DbSet<T_Medicen_Sale_Line> T_Medicen_Sale_Line { get; set; }
        public virtual DbSet<T_Purchase_Hedar> T_Purchase_Hedar { get; set; }
        public virtual DbSet<T_Purchase_Line> T_Purchase_Line { get; set; }
    }
}
