//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Db_Hospital_Management_EntityFramework.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Client_Registration
    {
        public int ClientId { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> ClientGlobalId { get; set; }
        public string ClientName { get; set; }
        public string ClientAddress { get; set; }
        public string ClientPhone { get; set; }
        public string ClientCity { get; set; }
        public string BusniessName { get; set; }
        public string ClientPan { get; set; }
        public string ClientRegistrationNo { get; set; }
        public string ClientGST { get; set; }
        public string ClientLogo { get; set; }
        public string ClientEmail { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ActiveFlag { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public Nullable<int> Attr3 { get; set; }
    }
}
