//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Db_Hospital_Management_EntityFramework.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Employee_Information
    {
        public int EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<int> EmployeeTitle { get; set; }
        public Nullable<int> EmployeeGender { get; set; }
        public string EmployeeName { get; set; }
        public int EmployeeDesignation { get; set; }
        public int EmployeeDepartment { get; set; }
        public Nullable<System.DateTime> EmployeeDob { get; set; }
        public Nullable<System.DateTime> EmployeeJoingDate { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeCity { get; set; }
        public string EmployeePan { get; set; }
        public string EmployeeAdharchard { get; set; }
        public string EmployeeAlternetNo { get; set; }
        public string EmployeeMobile { get; set; }
        public string EmployeeEmailId { get; set; }
        public Nullable<int> EmployeeBankName { get; set; }
        public string EmployeeAccountNo { get; set; }
        public string EmployeeIfscCode { get; set; }
        public Nullable<int> EmployeeBranch { get; set; }
        public string EmployeePhoto { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public string Attr3 { get; set; }
        public Nullable<int> Attr4 { get; set; }
    }
}
