//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Db_Hospital_Management_EntityFramework.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Item_Information
    {
        public int ItemId { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string ItemName { get; set; }
        public string ItemManufactionName { get; set; }
        public Nullable<int> ItemPacinking { get; set; }
        public string ItemUseName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<System.DateTime> ItemStartDate { get; set; }
        public Nullable<System.DateTime> ItemEndDate { get; set; }
        public Nullable<int> ItemFirstUnit { get; set; }
        public Nullable<int> ItemSecondUnit { get; set; }
        public Nullable<decimal> ItemConversionFirstFactor { get; set; }
        public Nullable<decimal> ItemConversionSecondfactor { get; set; }
        public Nullable<bool> ItemIsStockebal { get; set; }
        public Nullable<bool> ItemQualityCheck { get; set; }
        public Nullable<bool> ItemReturnPolicy { get; set; }
        public Nullable<decimal> ItemMinQTY { get; set; }
        public Nullable<decimal> ItemMaxQTY { get; set; }
        public string ItemHsnCode { get; set; }
        public Nullable<int> ItemPoType { get; set; }
        public Nullable<bool> ItemTaxApply { get; set; }
        public Nullable<decimal> ItemPoTaxGroup { get; set; }
        public Nullable<decimal> ItemSaleTaxGroup { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public string Attr3 { get; set; }
        public Nullable<int> Attr4 { get; set; }
        public Nullable<int> Attr5 { get; set; }
        public Nullable<int> Attr6 { get; set; }
    }
}
