//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Db_Hospital_Management_EntityFramework.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Packing
    {
        public int PackingId { get; set; }
        public string PackingName { get; set; }
        public Nullable<int> FirstPackingConvert { get; set; }
        public Nullable<int> SecondPackingConvert { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
    }
}
