//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Db_Hospital_Management_EntityFramework.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Tax_Type_Information
    {
        public int TaxId { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<int> TaxGroupId { get; set; }
    }
}
