//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Db_Hospital_Management_EntityFramework.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Medicen_Sale_Line
    {
        public int SaleLineId { get; set; }
        public Nullable<int> SaleHedarId { get; set; }
        public Nullable<int> PurchaseLineId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemBatch { get; set; }
        public string ItemPckg { get; set; }
        public Nullable<System.DateTime> ItemExpDate { get; set; }
        public string ItemMfg { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<decimal> ItemMrp { get; set; }
        public Nullable<decimal> ItemTotalAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> PaidUnpaid { get; set; }
        public Nullable<int> Attr1 { get; set; }
        public Nullable<decimal> Attr2 { get; set; }
        public string Attr3 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
