//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Db_Hospital_Management_EntityFramework.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Medicen_Sale_Hedar
    {
        public int Sale_Hedar_Id { get; set; }
        public Nullable<System.DateTime> Sale_Date { get; set; }
        public int Client_Id { get; set; }
        public int Global_Id { get; set; }
        public string Sale_Document_Number { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<decimal> Discount_Percentage { get; set; }
        public Nullable<decimal> Discount_In_Rupees { get; set; }
        public Nullable<decimal> Discount_Amount_Percentage { get; set; }
        public Nullable<decimal> Discount_Amount_Rupees { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string Contact_No { get; set; }
        public string Dr_Name { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Attr1 { get; set; }
        public string Attr2 { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Updated_By { get; set; }
    }
}
